// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA175ja9Cty5TrPRkKxMPbH8UbvpfxpWDE',
    appId: '1:146155693187:android:2a256e45745220995ae7b6',
    messagingSenderId: '146155693187',
    projectId: 'empoweromics-f8c18',
    storageBucket: 'empoweromics-f8c18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkj_hMbHRsPRTjOK_1PEk4yCA5tbvpc_E',
    appId: '1:146155693187:ios:3ba3259f8e2bf5625ae7b6',
    messagingSenderId: '146155693187',
    projectId: 'empoweromics-f8c18',
    storageBucket: 'empoweromics-f8c18.appspot.com',
    iosClientId: '146155693187-hb1dmtg52jbehpe15dp01kiqeeanaqj8.apps.googleusercontent.com',
    iosBundleId: 'com.empoweromics',
  );
}
