import 'package:get/get.dart';

class Strings extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "app_name": "Empoweromics",
          "main_screen": "Main screen",
          "installment_calculator": "Installment calculator",
          "login": "Login",
          "overview": "Overview",
          "purchase_new_unit": "Purchase new unit",
          "extend_installment_tenor": "Extend installment tenor",
          "refinance_buy_lease_back": "Refinance ,buy &lease back",
          "features": "Features",
          "tenor_up_to": "Tenor up to",
          "ftv_up_to": "FTV up to",
          "financed_amount_up_to": "Financed amount up to",
          "eligibility_criteria": "Eligibility criteria",
          "egyptians": "Egyptians",
          "expats": "Expats",
          "non_egyptian_resident": "Non-Egyptian (resident)",
          "login_with_your_phone_number": "Login with your phone number",
          "notice": "*Notice",
          "completing_the_registration_you_agree": " completing the registration, you agree ",
          "on_terms_and_conditions_in_the_empoweromics": "on terms and conditions in the Empoweromics",
          "insert_mobile_number": "Insert mobile number",
          "or": "Or",
          "years": "Years",
          "percentge": "%",
          "mn": "Mn",
          "english_language_btn": "English",
          "arabic_language_btn": "Arabic",
          "select_service": "Select service",
          "calculate_your_installments": "Calculate your installments",
          "monthly_installment_as_per_finance_amount_value": "Monthly Installment as per finance amount value",
          "unit_type": "Unit type (type of product)",
          "age": "age",
          "tenor_in_years": "Tenor in years",
          "finance_value": "Finance value",
          "unit_value": "Unit value",
          "calculate": "calculate",
          "errorRequired": "Required",
          "your_age_plus_tenor_period_must_not_exceed65_years": "Your age plus tenor period must not exceed 65 years",
          "total_monthly_payment": "Total monthly payment",

        },
        'ar_EG': {
          "app_name": "إمباوراوميكس",
          "main_screen": "الصفحة الرئيسية",
          "installment_calculator": "حساب الأقساط",
          "login": "تسجيل الدخول",
          "overview": "نظرة عامة",
          "purchase_new_unit": "تمويل شراء وحدات",
          "extend_installment_tenor": "مد فترة التمويل",
          "refinance_buy_lease_back": "اعادة تمويل الوحدات",
          "features": "الخصائص والمميزات",
          "tenor_up_to": "فتره التمويل تصل الى",
          "ftv_up_to": "تمويل يصل الى",
          "financed_amount_up_to": "قيمه التمويل تصل الى",
          "eligibility_criteria": "شروط التقديم",
          "egyptians": "مصريين",
          "expats": "المصريين العاملين بالخارج",
          "non_egyptian_resident": "الأجانب المقيمين في مصر",
          "login_with_your_phone_number": "سجل الدخول باستخدام رقم هاتفك",
          "notice": "*ملحوظة",
          "completing_the_registration_you_agree": " بإكمالك التسجيل فأنت موافق ",
          "on_terms_and_conditions_in_the_empoweromics": "على الشروط والأحكام في إمباوراوميكس",
          "insert_mobile_number": "أدخل رقم الهاتف",
          "or": "أو",
          "years": "سنة",
          "percentge": "% من قيمه الوحدة",
          "mn": "مليون جنيه مصري",
          "english_language_btn": "انجليزي",
          "arabic_language_btn": "عربي",
          "select_service": "اختر الخدمة",
          "calculate_your_installments": "حساب الاقساط الخاصة بك",
          "monthly_installment_as_per_finance_amount_value": "القسط الشهري حسب قيمة مبلغ التمويل",
          "unit_type": "نوع الوحدة",
          "age": "سن العميل (بالسنين)",
          "tenor_in_years": "مدة التمويل (بالسنين)",
          "finance_value": "مبلغ التمويل(بالجنية المصري)",
          "unit_value": "ثمن الوحده",
          "calculate": "احسب",
          "errorRequired": "مطلوب",
          "your_age_plus_tenor_period_must_not_exceed65_years": "Your age plus tenor period must not exceed 65 years",
          "total_monthly_payment": "إجمالي الدفعة الشهرية",

        }
      };
}
